### ISSUE TITLE
Vladislav_Ponomaryov_EN3_B04

### ISSUE THREAD

**Issue by Dakebro** [konsteacher/finalexam#277]
Он не успел сфотаться агай
![img_4518](https://cloud.githubusercontent.com/assets/16364063/12047651/4434ff7a-aef9-11e5-9239-69052a429af2.JPG)
.

**Comment by konsteacher** [comment]
А я не успел поставить...
On Dec 30, 2015 1:29 PM, "EN3_B04 Dinsultan Absattar" <
notifications@github.com> wrote:

> Он не успел сфотаться агай
> [image: img_4518]
> <https://camo.githubusercontent.com/0c00e4dd3d7188c17172c2a8f00f277cd3e43600/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31363336343036332f31323034373635312f34343334666637612d616566392d313165352d393233392d3639303532613432396166324a5047>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/konsteacher/finalexam/issues/277>.
>

-- 
  Think Green - don't print this email unless you really need to
